export enum DataType {
    Text = 1,
    String = 2,
    Integer = 3,
    Float = 4,
    Decimal = 5,
    Date = 6,
    Sequence = 7,
    List = 8,
    MultiValueList = 9,
    Boolean = 10,
    Image = 11,
    Item = 12,
    FormattedText = 13,
    File = 14,
    Relationship = 15
  }
  
  export enum ControlType {
    Text = 1,
    Numeric = 2,
    Date = 3,
    Label = 4,
    CheckGroup = 5,
    RadioGroup = 6,
    DropDown = 7,
    Image = 9,
    Video = 10,
    Rating = 11,
    Signature = 12,
    TextArea = 16,
    RichText = 17,
    Link = 18,
    Composite = 19,
    Lookup = 22,
    SingleSelectionMatrix = 23,
    MultipleSelectionMatrix = 24,
    DynamicMatrix = 25,
    Document = 26,
    Section = 27,
    Group = 28,
    Item = 29,
    Table = 30,
    File = 31,
    CheckBox = 32,
    ButtonGroup= 33
  }